apiVersion: batch/v1
kind: Job
metadata:
  namespace: default
  name: myjob
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - image: cgr.dev/chainguard/cosign:latest-dev@sha256:30bdad3fbb890ca46b9acd806af12c9f822b0d4f7c4c3d7e4e83e490782ac593
      - image: cgr.dev/chainguard/python:latest@sha256:fd728e07eea2a5ea9acef0050720485f2a9738cef52ec8931e18cf94ba12c7e2
      - image: registry.access.redhat.com/ubi9/openjdk-17-runtime:latest@sha256:3029219b1bf9956f72d1cc7b2da3192c46476aefbb6ca9a850e6a07eaf504374
