name: Image digest update

on:
  workflow_dispatch:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest

    permissions:
      contents: write # to push the updates
      pull-requests: write # to open Pull requests
      id-token: write # used to sign the commits using gitsign

    steps:
    - uses: actions/checkout@v4

    - uses: chainguard-dev/setup-chainctl@v0
      with:
        identity: "326bcde5903252f3ae2fe01c691b5a50f7046b5d/6d4c52015ce89613"

    - uses: ribbybibby/digestabot@updated-images
      id: digestabot
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: ribbybibby/digestabot-diff@impl
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        json: ${{ steps.digestabot.outputs.json }}
        pull_request_number: ${{ steps.digestabot.outputs.pull_request_number }}
